notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: xenial
addons:
  apt:
    packages:
      - chromium-chromedriver
matrix:
  include:
    - name: "Ruby 2.4"
      rvm: 2.4
    - name: "Ruby 2.5"
      rvm: 2.5
    - name: "Ruby 2.6"
      rvm: 2.6
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt purge -y google-chrome-stable
  - find / -name "*chrome*"
script:
  - bundle exec bin/rails groonga:migrate
  - bundle exec bin/rails groonga:test:prepare
  - bundle exec bin/rails test
